#!/bin/sh

set -eu

npm run build

if [ -n "$(git status --porcelain dist)" ]; then
    git add -- dist
    git commit --only --no-verify -m "generate dist files" -- dist

    echo "Generated and committed dist files. Run git push again to push the new commit."
    exit 1
fi
